### ISSUE TITLE
Theme renderer error - image_url

### ISSUE THREAD

**Issue by haietza** [DigiDago/moodle-block_admin_presets#12]
Seeing a theme renderer error on pages the block is placed (Moodle 3.2 needs pix_url still - only use image_url in 3.3):

Exception - Call to undefined method theme_boost\output\core_renderer::image_url()
Debug info: 
Error code: generalexceptionmessage
Stack trace:
line 54 of /blocks/admin_presets/block_admin_presets.php: Error thrown
line 709 of /blocks/moodleblock.class.php: call to block_admin_presets->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_list->formatted_contents()
line 1187 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 356 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 3899 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 41 of /theme/asu/layout/columns2.php: call to core_renderer->blocks()
line 1110 of /lib/outputrenderers.php: call to include()
line 1040 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 114 of /index.php: call to core_renderer->header()

**Comment by CrymSonir** [comment]
Hi,
la plupart ce ticket avait été en grosse partie réglé dans un ticket passé. le reste a été fixé dans la dernière version du plugin et fera prochainement l'objet d'une mise à jour sur le site moodle.

```
image_url was used instead of pix_icon
```

**Comment by oluniyi70** [comment]
I just installed adaptable theme and it appears it works fine. I tried to log out, this is what I am seen - error Exception - Call to undefined method theme_adaptable\output\core_renderer::firstview_fakeblocks()
Can anyone shed light on what needs to rectify the error

**Comment by CrymSonir** [comment]
> I just installed adaptable theme and it appears it works fine. I tried to log out, this is what I am seen - error Exception - Call to undefined method theme_adaptable\output\core_renderer::firstview_fakeblocks() Can anyone shed light on what needs to rectify the error

It seems that your error is related to the adaptable theme format, a method called would not be present in the theme. Perhaps an update of your theme will solve the problem possibly purging the cache of your moodle. But it doesn't seem to concern our plugin.
