### ISSUE TITLE
I installed on Bb OpenLMS.

### ISSUE THREAD

**Issue by syusanjun** [DigiDago/moodle-block_admin_presets#22]
I installed on Bb OpenLMS.

CSS class styles name should contain the prefix block_admin_presets to avoid collisions.

The Javascript code should change module.js, Since version 2.9, Moodle supports Javascript modules written using the Asynchronous Module Definition (AMD) API (https://docs.moodle.org/dev/Javascript_Modules)

Avoid to use global php variable $_POST on admin_presets/lib/admin_presets_export.class.php”

**Comment by CrymSonir** [comment]
Hello,
A prefix has been added to avoid collisions in the future.
$ _POST will no longer be used directly and will now pass through the filter_input_array () function.
The transition from module.js to amd will take more time.
Sorry for the delay.
Best regards,
