### ISSUE TITLE
missing parameter "auth_cas | contexts" in export ?

### ISSUE THREAD

**Issue by ensuspension** [DigiDago/moodle-block_admin_presets#26]
Hi,
thanks for your works.
 in the export file, one parameter is missing Plugins->authentication->CAS server (SSO)->contexts

is it a choice or an oversight?
best regards

**Comment by CrymSonir** [comment]
Hello,
Sorry for the delay in my response.
I confirm that some "sensible settings" are avoid.
So yes indeed it was a choice :)
Best regards

**Comment by CrymSonir** [comment]
I fixed this issue. It will be deployed on the next version of the plugin.
Best regards,
