### ISSUE TITLE
Settings are missing

### ISSUE THREAD

**Issue by clementpr** [DigiDago/moodle-block_admin_presets#31]
**Describe the bug**
Some settings are missing when we "load" import

**To Reproduce**
1. Go to admin preset and export settings
2. Go to an other webiste and go use admin preset to import
3. You see all settings on preview page
4. When we "load" import, some settings are missing. For example, we have "block, atto, filter, format, enrol, log" but not "theme" setting.

**Expected behavior**
Possibility to import all settings exported

**Comment by azmatksa** [comment]
Hi @DigiDagoFirst,  I tried to export setting and during export I can see theme option but theme settings not appearing after import into other other instance. Issue is same as mentioned by @clementpr
