### ISSUE TITLE
pix_url is deprecated in 3.3

### ISSUE THREAD

**Issue by haietza** [DigiDago/moodle-block_admin_presets#7]
Installed the block on 3.3+ and received the following debug output:

pix_url is deprecated. Use image_url for images and pix_icon for icons.
line 267 of /lib/outputrenderers.php: call to debugging()
line 34 of /blocks/admin_presets/block_admin_presets.php: call to renderer_base->pix_url()
line 704 of /blocks/moodleblock.class.php: call to block_admin_presets->get_content()
line 251 of /blocks/moodleblock.class.php: call to block_list->is_empty()
line 1197 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1249 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 3839 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 41 of /theme/asu/layout/columns2.php: call to core_renderer->blocks()
line 1162 of /lib/outputrenderers.php: call to include()
line 1092 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 114 of /index.php: call to core_renderer->header()

**Comment by clementpr** [comment]
Yes, we see that. We try to fix that next week.
